# This is a basic workflow to help you get started with Actions

name: Publish helm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: alpine/git

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # Runs a single command using the runners shell
      - name: Package
        run: |
          mkdir -p public
          cd public
          helm package ../chart/kafka-connectors
          cd -

      - name: Generate index
        run: |
          cd public
          helm repo index . --url ${{ format('https://{0}.github.io/{1}', github.repository_owner, 'kafka-connect-jdbc-sink') }}
          ls -l
          cat index.yaml
          cd -

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
